name: Build
concurrency:
  group: "master-build"
  #cancel-in-progress: true

on:
  push:
    branches: [ jclab-main ]
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      ARCH: amd64
    steps:
    - uses: actions/checkout@v3
    - run: |
        git fetch --prune --unshallow
        mkdir build
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Download meta 🔧
      uses: luet-lab/luet-github-action@master
      with:
        FINAL_REPO: ghcr.io/jclab-joseph/kairos-packages
        REPOSITORY_TYPE: docker
        downloadAllMeta: true
        downloadFromList: true
        downloadMeta: true
    - name: Build packages 🔧
      uses: luet-lab/luet-github-action@master
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/jclab-main' }}
      with:
        build: true
        fromIndex: true
        onlyMissing: true
        FINAL_REPO: ghcr.io/jclab-joseph/kairos-packages
        DOCKER_USERNAME: ${{ github.repository_owner }}
        DOCKER_PASSWORD: ${{ secrets.CR_PAT }}
        DOCKER_ENDPOINT: ghcr.io
        REPOSITORY_TYPE: docker
        pushFinalImages: true
        pushCache: true
    - name: Create repo 🔧
      uses: luet-lab/luet-github-action@master
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/jclab-main' }}
      with:
        FINAL_REPO: ghcr.io/jclab-joseph/kairos-packages
        DOCKER_USERNAME: ${{ github.repository_owner }}
        DOCKER_PASSWORD: ${{ secrets.CR_PAT }}
        DOCKER_ENDPOINT: ghcr.io
        REPOSITORY_TYPE: docker
        createRepo: true
        pushCache: true
